### ISSUE TITLE
Header nav <ul> kinda funky

### ISSUE THREAD

**Issue by derrickshowers** [sarahlshowers/kevin-smith-transpotation-group#23]
Technically, the child element of a `<ul>` should always be an `<li>`. In the header, you have something like this:

```
<ul>
    <a>
        <li>
        </li>
    </a>
</ul>
```

You should probably try to find a way to swap the `<a>` and the `<li>` so that the html is valid. That will also help constrain the width of the clickable area, meaning you should just be able to click on the word (e.g. FLEET, SERVICES), not the space to the side of it.

**Comment by sarahlshowers** [comment]
Fix implemented, closing
